# Generated by Django 5.1.4 on 2025-02-20 10:14

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0006_serviceprovided_servicerequest'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MechanicProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('date_of_birth', models.DateField()),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='mechanic_profiles/')),
                ('contact_no', models.CharField(max_length=10, unique=True, validators=[django.core.validators.RegexValidator(message='Mobile number must be exactly 10 digits', regex='^\\d{10}$')])),
                ('aadhar_id', models.CharField(max_length=12, unique=True, validators=[django.core.validators.RegexValidator(message='Aadhar number must be exactly 12 digits', regex='^\\d{12}$')])),
                ('alternate_contact', models.CharField(blank=True, max_length=10, null=True)),
                ('experience', models.PositiveIntegerField()),
                ('address', models.TextField()),
                ('state', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('district', models.CharField(max_length=255)),
                ('specialization', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Home.serviceprovided')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
