# Generated by Django 5.1.4 on 2025-02-20 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0007_mechanicprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mechanicprofile',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
    ]
