# Generated by Django 5.1.4 on 2025-02-20 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0008_alter_mechanicprofile_date_of_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mechanicprofile',
            name='experience',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
