# Generated by Django 5.1.4 on 2025-03-03 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0011_contactmessage'),
    ]

    operations = [
        migrations.CreateModel(
            name='MechanicNum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Mob_num', models.CharField(max_length=15)),
            ],
        ),
    ]
