# Generated by Django 5.1.4 on 2025-03-06 05:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0012_mechanicnum'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='mobile',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='mechanic',
            name='mobile',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='mechanicprofile',
            name='alternate_contact',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='mechanicprofile',
            name='contact_no',
            field=models.CharField(max_length=15, unique=True, validators=[django.core.validators.RegexValidator(message='Enter a valid number ', regex='^\\d{10,15}$')]),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='contact_number',
            field=models.CharField(max_length=15),
        ),
    ]
