# Generated by Django 5.1.2 on 2025-03-12 06:00

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0014_sparepart_mechanictaskupdate'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatusUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('In Progress', 'In Progress'), ('Completed', 'Completed')], default='Pending', max_length=20)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('mechanic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Home.mechanicprofile')),
                ('service_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Home.servicerequest')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_updates', to='Home.taskassignment')),
            ],
        ),
    ]
