# Generated by Django 5.1.2 on 2025-03-21 09:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0015_statusupdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mechanicprofile',
            name='contact_no',
            field=models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message='Enter a valid number ', regex='^\\d{10,15}$')]),
        ),
    ]
