# Generated by Django 5.1.2 on 2025-03-21 09:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0016_alter_mechanicprofile_contact_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mechanicprofile',
            name='aadhar_id',
            field=models.CharField(max_length=12, validators=[django.core.validators.RegexValidator(message='Aadhar number must be exactly 12 digits', regex='^\\d{12}$')]),
        ),
    ]
