# Generated by Django 5.1.2 on 2025-03-22 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0018_alter_mechanicprofile_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mechanicprofile',
            name='contact_no',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
