# Generated by Django 5.1.2 on 2025-03-22 16:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0019_alter_mechanicprofile_contact_no'),
    ]

    operations = [
        migrations.CreateModel(
            name='MechanicDetailsFill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed_date', models.DateField()),
                ('reached_time', models.CharField(blank=True, choices=[('1:00 AM', '1:00 AM'), ('1:00 PM', '1:00 PM'), ('2:00 AM', '2:00 AM'), ('2:00 PM', '2:00 PM'), ('3:00 AM', '3:00 AM'), ('3:00 PM', '3:00 PM'), ('4:00 AM', '4:00 AM'), ('4:00 PM', '4:00 PM'), ('5:00 AM', '5:00 AM'), ('5:00 PM', '5:00 PM'), ('6:00 AM', '6:00 AM'), ('6:00 PM', '6:00 PM'), ('7:00 AM', '7:00 AM'), ('7:00 PM', '7:00 PM'), ('8:00 AM', '8:00 AM'), ('8:00 PM', '8:00 PM'), ('9:00 AM', '9:00 AM'), ('9:00 PM', '9:00 PM'), ('10:00 AM', '10:00 AM'), ('10:00 PM', '10:00 PM'), ('11:00 AM', '11:00 AM'), ('11:00 PM', '11:00 PM'), ('12:00 AM', '12:00 AM'), ('12:00 PM', '12:00 PM')], max_length=10, null=True)),
                ('finished_time', models.CharField(blank=True, choices=[('1:00 AM', '1:00 AM'), ('1:00 PM', '1:00 PM'), ('2:00 AM', '2:00 AM'), ('2:00 PM', '2:00 PM'), ('3:00 AM', '3:00 AM'), ('3:00 PM', '3:00 PM'), ('4:00 AM', '4:00 AM'), ('4:00 PM', '4:00 PM'), ('5:00 AM', '5:00 AM'), ('5:00 PM', '5:00 PM'), ('6:00 AM', '6:00 AM'), ('6:00 PM', '6:00 PM'), ('7:00 AM', '7:00 AM'), ('7:00 PM', '7:00 PM'), ('8:00 AM', '8:00 AM'), ('8:00 PM', '8:00 PM'), ('9:00 AM', '9:00 AM'), ('9:00 PM', '9:00 PM'), ('10:00 AM', '10:00 AM'), ('10:00 PM', '10:00 PM'), ('11:00 AM', '11:00 AM'), ('11:00 PM', '11:00 PM'), ('12:00 AM', '12:00 AM'), ('12:00 PM', '12:00 PM')], max_length=10, null=True)),
                ('before_image', models.ImageField(blank=True, null=True, upload_to='service_pics/')),
                ('after_image', models.ImageField(blank=True, null=True, upload_to='service_pics/')),
                ('mechanic_notes', models.TextField(blank=True, null=True)),
                ('total_duration', models.DurationField(blank=True, editable=False, null=True)),
                ('mechanic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Home.mechanicprofile')),
                ('service_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Home.servicerequest')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mechanic_fill_details', to='Home.taskassignment')),
                ('used_spare_parts', models.ManyToManyField(blank=True, to='Home.sparepart')),
            ],
        ),
    ]
