# Generated by Django 5.1.2 on 2025-03-22 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0020_mechanicdetailsfill'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mechanicdetailsfill',
            name='completed_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
