# Generated by Django 5.1.2 on 2025-03-24 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0024_alter_feedback_mechanic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='overall_experience',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='pricing_satisfaction',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='problem_resolution',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='service_quality',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='staff_behavior',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='wait_time',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
