# Generated by Django 5.1.2 on 2025-03-26 06:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0025_alter_feedback_overall_experience_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MechanicAlertStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_status', models.CharField(choices=[('done', '✅ Done'), ('not_done', '❌ Not Done')], default='not_done', max_length=10)),
                ('mechanic', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='alert_status', to='Home.mechanic')),
            ],
        ),
    ]
