# Generated by Django 5.1.2 on 2025-04-01 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0030_custpayment'),
    ]

    operations = [
        migrations.AddField(
            model_name='custpayment',
            name='order_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
